apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc-app
  template:
    metadata:
      labels:
        app: calc-app
    spec:
      containers:
        - name: calc
          image: calc-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
